In [1]:
import numpy as np

In [2]:
revenue = np.array([[180,200,220],[24,36,40],[12,18,20]])
expenses = np.array([[80,90,100],[10,16,20],[8,10,10]])

In [3]:
profit = revenue - expenses
print(profit)

[[100 110 120]
 [ 14  20  20]
 [  4   8  10]]


In [7]:
price_per_unit = np.array([[1000],[400],[1200]])
units = np.array([[30,40,50],[5,10,15],[2,5,7]])
print(price_per_unit.T)
print(units)

[[1000  400 1200]]
[[30 40 50]
 [ 5 10 15]
 [ 2  5  7]]


In [8]:
total_sale = price_per_unit.T @ units
print(total_sale)

[[34400 50000 64400]]


In [9]:
rev = np.array([[200,220,250],[68,79,105],[110,140,180],[80,85,90]])

In [10]:
rev

array([[200, 220, 250],
       [ 68,  79, 105],
       [110, 140, 180],
       [ 80,  85,  90]])

In [11]:
inr = 75
rev_inr = rev * inr

In [13]:
rev_inr

array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])